# Workflow to register a new application deployment with Raygun.

# The workflow is triggered when a tag with the specified format is pushed to
# GitHub. The tag should be formatted as a prefix followed by the version
# number. For example: "prod/1.0.0"
#
# To use this workflow, you must:
#
# 1. Make sure the tag prefix is set correctly below. The default is "prod/".
#
# 2. Add two "Action secrets" in the GitHub repository settings:
#
#    * RAYGUN_APIKEY = the API key for the Raygun project
#    * RAYGUN_AUTHTOKEN = a "Personal Access Token" for your user account with
#      the `deployments:write` scope (generate a PAT at https://app.raygun.com/user/tokens)
#
# Learn more about Raygun Deployment Tracking at:
# https://raygun.com/documentation/product-guides/deployment-tracking/overview/
#
# Learn more about Raygun Personal Access Tokens at:
# https://raygun.com/documentation/accounts-billing/your-settings/#personal-access-tokens

name: Raygun Deployment Tracking

on:
  push:
    # Update this line with the desired tag format, e.g., "prod/*"
    tags: [prod/*]

jobs:
  raygun-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version number
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Send to the Raygun Deployments API
        id: send_deployment
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.raygun.com/v3/applications/api-key/${{ secrets.RAYGUN_APIKEY }}/deployments
          method: POST
          bearerToken: ${{ secrets.RAYGUN_AUTHTOKEN }}
          data: >-
            {
              "version": "${{ steps.get_version.outputs.VERSION }}",
              "ownerName": "${{ github.event.pusher.name }}",
              "emailAddress": "${{ github.event.pusher.email }}",
              "scmIdentifier": "${{ github.sha }}",
              "scmType": "GitHub"
            }

      - name: Show response
        run: echo ${{ steps.send_deployment.outputs.response }}
